project:
  type: website

website:
  title: "CIS 115 Information Technology and Society"
  site-url: "https://jrladd.com/CIS115"
  favicon: assets/favicon.svg
  search: false
  navbar:
    right:
      - text: "Schedule & Readings"
        href: schedule.qmd
      - text: "Assignments"
        href: assignments.qmd
      - text: "Course Policies"
        href: policies.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    toc: false
