---
title: "Information Technology and Society"
subtitle: '<a class="btn btn-outline-info" style="color: white;" href="schedule.qmd">Schedule</a> <a class="btn btn-outline-info" style="color: white;" href="assignments.qmd">Assignments</a> <a class="btn btn-outline-info" style="color: white;" href="policies.qmd">Course Policies</a> <a class="btn btn-outline-info" style="color: white;" href="https://sakai.washjeff.edu">Sakai</a>'
toc: false
title-block-banner: assets/images/eniac-banner.png
title-block-banner-color: white
---

::: {.card .border-info .mb-3}

:::: {.card-body}

CIS 115. Washington & Jefferson College. Spring 2026.  
**Meeting Time: MWF 10:20-11:30am**

Dr. Ladd's Student Drop-In Hours: M 1pm-3pm, Th 11-12pm in TECH 201  
or email for appointment, [jladd@washjeff.edu](mailto:jladd@washjeff.edu)

::::

:::

## Course Description

How have information technologies shaped our society? How has societal change affected the development of new technologies?

In this survey of the history of technology, we will examine information technology innovations that changed society in fundamental ways. Topics within the history of information technology include the development of the integrated circuit, the personal computer, the Internet and the World Wide Web, etc. Topics within the history of technology (broadly defined) include ethical, legal, environmental, and feminist issues involved in the development and implementation of new technologies. The course entails a combination of historical overview and a number of individual case studies of technology development and implementation. The latter will focus on issues of leadership, the identification and solution of complex problems, and the unexpected consequences of technological advances.

## Learning Goals

At the end of this course, you will be able to:

- Describe the role of computing technologies in solving problems of storing, retrieving, transmitting, and analyzing information
- Understand today's information technologies within the context of historical efforts to communicate knowledge and solve problems
- Critically evaluate the claims of new technologies that seek to improve daily life
- Write about computing technologies and their significance in an informative manner to a non-technical audience.

<small>Marlyn Meltzer and Ruth Teitelbaum reprogram ENIAC in 1946. Photo credit: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Reprogramming_ENIAC.png)</small>