---
title: "Schedule & Readings"
---

::: {.column-margin}
### Note on the schedule

*Keep in mind that some of this schedule could change throughout the semester. However, if anything changes I'll update this page, and I'll be sure to give you plenty of advance notice.*

### Books

- Ceruzzi, Paul E. *Computing: A Concise History*. MIT Press, 2012. [Available for free from the W&J Library!](https://go.openathens.net/redirector/washjeff.edu?url=https%3A%2F%2Fsearch.ebscohost.com%2Flogin.aspx%3Fdirect%3Dtrue%26scope%3Dsite%26db%3Dnlebk%26db%3Dnlabk%26AN%3D463391)
- Postman, Neil. *Technopoly: The Surrender of Culture to Technology*. New York: Vintage, 1992.
- Sloan, Robin. *Mr. Penumbra's 24-Hour Bookstore*. New York: Picador, 2013.
:::

## Class Schedule

**All course texts are available as PDFs in Sakai under Resources. If any link below does not work, a corresponding PDF is available on Sakai.**

Dates|Monday|Wednesday|Friday
---|-------|-----|---
||**Unit 1: Information & Technology**
26–28 Aug.|NO CLASS on Monday|Introductions and Course Theme.|[***Make a Stop Sign***](exercises/stopsign.qmd). Excerpt from *Phaedrus* (pdf).
31 Aug.–4 Sept.|O'Donnell, "From the Codex to the Homepage" (pdf).|*Computing*: Introduction and Ch. 1 & 2.|[***Send a Secret Message***](exercises/secret.qmd). Standage, "The Mother of All Networks" (pdf).|
9–11 Sept.|NO CLASS on Monday.|*Computing*: Ch. 3 & 4.|***Learn Binary***. Reid, "The Real Miracle" (pdf).
14–18 Sept.|*Computing*: Ch. 5, 6, & 7. |Bush, "[As We May Think.](http://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/)" Wright, "[The Secret History of Hypertext](https://www.theatlantic.com/technology/archive/2014/05/in-search-of-the-proto-memex/371385/)." (pdf)|Discussion/Research for [Historical Essay](assignments/historical-essay.qmd). (**Meet in the Library classroom!**)
21–25 Sept.|Abbate, "Cold War and White Heat." (pdf).|Planet Money: “[When Women Stopped Coding](https://www.npr.org/sections/money/2014/10/17/356944145/episode-576-when-women-stopped-coding).”|**Exam on Unit 1**
||**Unit 2: Technology & Society**
28 Sept.–2 Oct.|Kirschenbaum, "Unseen Hands" (pdf).|Matusow, "The Beast of Business" (pdf).|**[HISTORICAL ESSAY I](assignments/historical-essay.qmd) DUE**. Peer Review and Revision Planning.
5–9 Oct.|Carr, "[Is Google Making Us Stupid?](http://www.theatlantic.com/magazine/archive/2008/07/is-google-making-us-stupid/306868/)" (pdf).|NO CLASS MEETING.|[***Explore Search Engines***](exercises/search.qmd). Noble: [TEDx Talk](https://youtu.be/UXuJ8yQf6dI) (WARNING: This video is about the problem of racial stereotypes and misogyny and contains some graphic content). Bowles, "[Overlooked No More: Karen Sparck Jones, Who Established the Basis for Search Engines](https://www.nytimes.com/2019/01/02/obituaries/karen-sparck-jones-overlooked.html)."
12-16 Oct.|Hafner, "[History, Digitized (and Abridged)](http://www.nytimes.com/2007/03/10/business/yourmoney/11archive.html?ref=business)." Cerf: [TEDx Talk](https://www.youtube.com/watch?reload=9&v=GV0A82TCrf0)|[Archive LibGuide](https://libguides.washjeff.edu/c.php?g=1494112&p=11157473) **Meet in the Library Archives *at 10:30am***|Historical Essay Conferences (by Appt.)
||**Unit 3: Living with Technology**
21-23 Oct.|NO CLASS (Fall Break)|Sloan, *Mr. Penumbra's 24-Hour Bookstore* (pgs. 1-122, to the end of Part I, The Bookstore).|[***Build a Book***](exercises/book.qmd). *Penumbra* (pgs. 123-202, through *The Dragon-Song Chronicles, Volume II*).
26-30 Oct.|*Penumbra* (pgs. 202-288, to the end of the book).|Weinberger, *Everything is Miscellaneous* (pdf).| **[HISTORICAL ESSAY II](assignments/historical-essay-revision.qmd) DUE**. ***Spot the Troll***. Chen, “[The Agency](https://www.nytimes.com/2015/06/07/magazine/the-agency.html).”
2–6 Nov.|McNeill, "[The Community of Everybody and Nobody](https://live.mcachicago.org/publications/blog/2018/the-community-of-everybody-and-nobody)."|Lessig, "The Vision for the Creative Commons" (pdf pgs 36-49). Lessig: [TED Talk](https://www.ted.com/talks/lawrence_lessig_laws_that_choke_creativity).|***Research Tech Patents.*** Lee, “[A Patent Lie](http://www.nytimes.com/2007/06/09/opinion/09lee.html?_r=1&oref=slogin).” This American Life: “[When Patents Attack: Part II](http://www.thisamericanlife.org/radio-archives/episode/496/when-patents-attack-part-two).”
9–13 Nov.|Weingart, "[The Route of a Text Message, a Love Story](https://www.vice.com/en/article/the-route-of-a-text-message-a-love-story/).|Postman, Introduction & Ch. 1.|Postman, Ch. 2 & 3.
16–20 Nov.|Postman, Ch. 5 & 6.|Postman, Ch. 8 & 9.|**Exam on Units 2 & 3**
||**Unit 4: Futurism (Past & Present)**
23 Nov.|Doctorow, "[Tiktok's Enshittification](https://pluralistic.net/2023/01/21/potemkin-ai/#hey-guys)."|NO CLASS (Thanksgiving Break)|NO CLASS (Thanksgiving Break)
30 Nov.–4 Dec.|Roose, "[The Robots are Coming for Phil in Accounting](https://www.nytimes.com/2021/03/06/business/the-robots-are-coming-for-phil-in-accounting.html)." Watch *Transcendent Man* in class.|danah boyd, "[Social Media is Now Parasocial Media](https://journals.sagepub.com/doi/10.1177/20563051261437487)" Continue *Transcendent Man*.|Chiang, "ChatGPT is a Blurry JPEG of the Web" (pdf). Finish *Transcendent Man*.
7 Dec.|Peer Review of [Futurist Essay](assignments/futurist-essay.qmd).
Saturday 12 Dec. 2-5pm|FINAL EXAM PERIOD. Write the **[FUTURIST ESSAY](assignments/futurist-essay.qmd)**

: {.striped .hover tbl-colwidths="[10,35,25,25]"}