---
title: "Historical Essay I"
date: 2022-09-23
---

**Complete by: Friday 20 Feb., at class time.**

## The Prompt

Write an essay using one or more contemporary (primary) print (or video) sources (advertisement, newspaper article, newsreel, etc.) from the early period of computing history that we have been discussing in class (1945-1995).  For example, find an advertisement for a business machine in a popular magazine from the 1970s (such as one of the ones on [our class LibGuide](https://libguides.washjeff.edu/CIS115)), and write about what the advertisement shows about the history and/or social phenomena of the time. Another way to approach this assignment is to decide about an event or invention you are interested in, and find one or more articles about the topic in the popular press of the time.

## The Details

The essay should have four paragraphs: an introduction, two body paragraphs, and a conclusion. In this essay, you are responsible for your own introduction strategy and thesis. Develop an interesting angle on the topic that is based in your own reflection upon the material. Focus each body paragraph on specific textual or visual features of your primary source. Spend time thinking not only about *what* your source is saying, but *how* your source is saying it.

To develop a thesis, you will need to think carefully about what your *primary source* is saying and why. A good thesis makes a clear historical **argument**; is specific, focused, and precise; and answers the question "so what?". A good start may be for you to figure out what argument you think the author/creator of your source is trying to make.

## The Research

For this essay, you must find a *primary source* using the library’s online databases. Here is a link to [the LibGuide for our class](https://libguides.washjeff.edu/CIS115).

Your primary source should be from the **same time period** as the technology, event, or phenomenon you're writing about. For example, if you're writing about the ENIAC, your primary source should be from the 1940s or 50s. If you're writing about the idea of the hyperlink, your article might be from the 1950s (i.e. around the time of Vannevar Bush's article) or it might be from the 1980s (i.e. around the invention of the Web).

Your primary source ***must*** be about one of the 20th century computing technologies, events, or social phenomena that we have covered in class. This period is roughly from the 1940s through the 1990s. This means you can't write about something like the telegraph (too early) or ChatGPT (too recent). If you're wondering whether your chosen topic is in the right time period, just ask me!

**Requirements**:

- Submit your essay to the assignment on [Sakai](//sakai.washjeff.edu).
- 4 paragraphs, 450-900 words
- Include the wordcount in the header of your paper
- At least one *library* source you found on your own, ideally using the [LibGuide](https://libguides.washjeff.edu/CIS115)
- Several integrated and correctly cited quotes from your source
- Double-spaced, readable font
- MLA Format & Citations
- PDF format (not a Word doc or other file type)
